version: "3.8"

services:
  songdb:
    container_name: edusongdb
    hostname: edusongdb
    image: mysql:8.0
    ports:
      - 8900:3306
    networks:
      - edufynet
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: songdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass

  albumdb:
    container_name: edualbumdb
    hostname: edualbumdb
    image: mysql:8.0
    ports:
      - 8901:3306
    networks:
      - edufynet
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: albumdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass

  creatordb:
    container_name: educreatordb
    hostname: educreatordb
    image: mysql:8.0
    ports:
      - 8903:3306
    networks:
      - edufynet
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: creatordb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass

networks:
  edufynet:
    name: edufynetwork
